### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "ro9er.nordqvist@gmail.com",
    "password": "hemlis"
}

### Find a particular user
Get http://localhost:3000/auth/2
